#
FROM busybox

#
# Create required path and add files
RUN mkdir -p /tmp/activationBase/
COPY data/activation_data.csv /tmp/activationBase/
COPY README.md /tmp/activationBase/

CMD ["sh"]# Use the busybox base image

